name: Wallet Backup

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 4 4,20 * *"
jobs:
  run:
    name: Do wallet backup
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run the script
        uses: addnab/docker-run-action@v3
        with:
          image: luisfelipe998/wallet-backup:latest
          options: -v ${{ github.workspace }}:/var/www -e EMAIL=${{secrets.EMAIL}} -e PASSWORD=${{secrets.PASSWORD}} -e STATUS_INVEST_EMAIL=${{secrets.STATUS_INVEST_EMAIL}} -e STATUS_INVEST_PASSWORD=${{secrets.STATUS_INVEST_PASSWORD}}
          run: |
            npm start
